live_config_reload = true

[env]
TERM = "alacritty-direct"

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
blur = true
decorations = "buttonless"
opacity = 0.9

[window.padding]
x = 0
y = 0
