k9s:
  cluster: gke_affluent-143623_us-central1-c_agency-production
  readOnly: false
  namespace:
    active: gen3
    lockFavorites: false
    favorites:
    - gen3
    - default
  view:
    active: po
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
