k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke_affluent-143623_us-central1-c_agency-production
  currentCluster: gke_affluent-143623_us-central1-c_agency-production
  clusters:
    gke_affluent-143623_us-central1-a_agency-staging:
      namespace:
        active: staging
        lockFavorites: false
        favorites:
        - staging
        - gen3
        - default
      view:
        active: context
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_affluent-143623_us-central1-a_publisher-staging:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: context
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_affluent-143623_us-central1-c_agency-production:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
        - all
        - ap
        - emea
        - dmipartners
        - entryusa
        - asos
        - agency-global
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_affluent-development_us-west1-a_crossplanezsrybaldxsfc3wr:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - aint1894
        - default
      view:
        active: cronjob
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/pc/v0pqcz41373d7xhv1fqklpt80000gn/T/k9s-screens-tim.shilov
